// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Activity interface {
	IsActivity()
}

type CareSession struct {
	ID          string              `json:"id"`
	Caregiver   *Caregiver          `json:"caregiver"`
	Status      CareSessionStatus   `json:"status"`
	StartedAt   time.Time           `json:"startedAt"`
	CompletedAt *time.Time          `json:"completedAt,omitempty"`
	Activities  []Activity          `json:"activities"`
	Notes       *string             `json:"notes,omitempty"`
	Summary     *CareSessionSummary `json:"summary"`
}

type CareSessionSummary struct {
	TotalFeeds         int32      `json:"totalFeeds"`
	TotalMl            int32      `json:"totalMl"`
	TotalDiaperChanges int32      `json:"totalDiaperChanges"`
	TotalSleepMinutes  int32      `json:"totalSleepMinutes"`
	LastFeedTime       *time.Time `json:"lastFeedTime,omitempty"`
	LastSleepTime      *time.Time `json:"lastSleepTime,omitempty"`
	CurrentlyAsleep    bool       `json:"currentlyAsleep"`
}

type Caregiver struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	DeviceID   string  `json:"deviceId"`
	DeviceName *string `json:"deviceName,omitempty"`
}

type DiaperActivity struct {
	ID            string         `json:"id"`
	ActivityType  ActivityType   `json:"activityType"`
	CreatedAt     time.Time      `json:"createdAt"`
	DiaperDetails *DiaperDetails `json:"diaperDetails,omitempty"`
}

func (DiaperActivity) IsActivity() {}

type DiaperDetails struct {
	ChangedAt time.Time `json:"changedAt"`
	HadPoop   bool      `json:"hadPoop"`
	HadPee    bool      `json:"hadPee"`
}

type FeedActivity struct {
	ID           string       `json:"id"`
	ActivityType ActivityType `json:"activityType"`
	CreatedAt    time.Time    `json:"createdAt"`
	FeedDetails  *FeedDetails `json:"feedDetails,omitempty"`
}

func (FeedActivity) IsActivity() {}

type FeedDetails struct {
	StartTime       time.Time  `json:"startTime"`
	EndTime         *time.Time `json:"endTime,omitempty"`
	AmountMl        *int32     `json:"amountMl,omitempty"`
	FeedType        *FeedType  `json:"feedType,omitempty"`
	DurationMinutes *int32     `json:"durationMinutes,omitempty"`
}

type NextFeedPrediction struct {
	PredictedTime    time.Time            `json:"predictedTime"`
	Confidence       PredictionConfidence `json:"confidence"`
	Reasoning        *string              `json:"reasoning,omitempty"`
	MinutesUntilFeed int32                `json:"minutesUntilFeed"`
}

type Query struct {
}

type SleepActivity struct {
	ID           string        `json:"id"`
	ActivityType ActivityType  `json:"activityType"`
	CreatedAt    time.Time     `json:"createdAt"`
	SleepDetails *SleepDetails `json:"sleepDetails,omitempty"`
}

func (SleepActivity) IsActivity() {}

type SleepDetails struct {
	StartTime       time.Time  `json:"startTime"`
	EndTime         *time.Time `json:"endTime,omitempty"`
	DurationMinutes *int32     `json:"durationMinutes,omitempty"`
	IsActive        bool       `json:"isActive"`
}

type ActivityType string

const (
	ActivityTypeFeed   ActivityType = "FEED"
	ActivityTypeDiaper ActivityType = "DIAPER"
	ActivityTypeSleep  ActivityType = "SLEEP"
)

var AllActivityType = []ActivityType{
	ActivityTypeFeed,
	ActivityTypeDiaper,
	ActivityTypeSleep,
}

func (e ActivityType) IsValid() bool {
	switch e {
	case ActivityTypeFeed, ActivityTypeDiaper, ActivityTypeSleep:
		return true
	}
	return false
}

func (e ActivityType) String() string {
	return string(e)
}

func (e *ActivityType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ActivityType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ActivityType", str)
	}
	return nil
}

func (e ActivityType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ActivityType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ActivityType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CareSessionStatus string

const (
	CareSessionStatusInProgress CareSessionStatus = "IN_PROGRESS"
	CareSessionStatusCompleted  CareSessionStatus = "COMPLETED"
)

var AllCareSessionStatus = []CareSessionStatus{
	CareSessionStatusInProgress,
	CareSessionStatusCompleted,
}

func (e CareSessionStatus) IsValid() bool {
	switch e {
	case CareSessionStatusInProgress, CareSessionStatusCompleted:
		return true
	}
	return false
}

func (e CareSessionStatus) String() string {
	return string(e)
}

func (e *CareSessionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CareSessionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CareSessionStatus", str)
	}
	return nil
}

func (e CareSessionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CareSessionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CareSessionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FeedType string

const (
	FeedTypeBreastMilk FeedType = "BREAST_MILK"
	FeedTypeFormula    FeedType = "FORMULA"
)

var AllFeedType = []FeedType{
	FeedTypeBreastMilk,
	FeedTypeFormula,
}

func (e FeedType) IsValid() bool {
	switch e {
	case FeedTypeBreastMilk, FeedTypeFormula:
		return true
	}
	return false
}

func (e FeedType) String() string {
	return string(e)
}

func (e *FeedType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FeedType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FeedType", str)
	}
	return nil
}

func (e FeedType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FeedType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FeedType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PredictionConfidence string

const (
	PredictionConfidenceHigh   PredictionConfidence = "HIGH"
	PredictionConfidenceMedium PredictionConfidence = "MEDIUM"
	PredictionConfidenceLow    PredictionConfidence = "LOW"
)

var AllPredictionConfidence = []PredictionConfidence{
	PredictionConfidenceHigh,
	PredictionConfidenceMedium,
	PredictionConfidenceLow,
}

func (e PredictionConfidence) IsValid() bool {
	switch e {
	case PredictionConfidenceHigh, PredictionConfidenceMedium, PredictionConfidenceLow:
		return true
	}
	return false
}

func (e PredictionConfidence) String() string {
	return string(e)
}

func (e *PredictionConfidence) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PredictionConfidence(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PredictionConfidence", str)
	}
	return nil
}

func (e PredictionConfidence) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PredictionConfidence) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PredictionConfidence) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
