// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Activity interface {
	IsActivity()
}

type ActivityInput struct {
	ActivityType  ActivityType        `json:"activityType"`
	FeedDetails   *FeedDetailsInput   `json:"feedDetails,omitempty"`
	DiaperDetails *DiaperDetailsInput `json:"diaperDetails,omitempty"`
	SleepDetails  *SleepDetailsInput  `json:"sleepDetails,omitempty"`
}

type AuthResult struct {
	Success   bool       `json:"success"`
	Family    *Family    `json:"family,omitempty"`
	Caregiver *Caregiver `json:"caregiver,omitempty"`
	Error     *string    `json:"error,omitempty"`
}

type BabyStatus struct {
	LastFeed   *FeedActivity   `json:"lastFeed,omitempty"`
	LastDiaper *DiaperActivity `json:"lastDiaper,omitempty"`
	LastSleep  *SleepActivity  `json:"lastSleep,omitempty"`
}

type CareSession struct {
	ID          string              `json:"id"`
	Caregiver   *Caregiver          `json:"caregiver"`
	FamilyID    string              `json:"familyId"`
	Status      CareSessionStatus   `json:"status"`
	StartedAt   time.Time           `json:"startedAt"`
	CompletedAt *time.Time          `json:"completedAt,omitempty"`
	Activities  []Activity          `json:"activities"`
	Notes       *string             `json:"notes,omitempty"`
	Summary     *CareSessionSummary `json:"summary"`
}

type CareSessionConnection struct {
	Edges    []*CareSessionEdge   `json:"edges"`
	PageInfo *CareSessionPageInfo `json:"pageInfo"`
}

type CareSessionEdge struct {
	Node   *CareSession `json:"node"`
	Cursor string       `json:"cursor"`
}

type CareSessionPageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type CareSessionSummary struct {
	TotalFeeds         int32      `json:"totalFeeds"`
	TotalMl            int32      `json:"totalMl"`
	TotalDiaperChanges int32      `json:"totalDiaperChanges"`
	TotalSleepMinutes  int32      `json:"totalSleepMinutes"`
	LastFeedTime       *time.Time `json:"lastFeedTime,omitempty"`
	LastSleepTime      *time.Time `json:"lastSleepTime,omitempty"`
	CurrentlyAsleep    bool       `json:"currentlyAsleep"`
}

type Caregiver struct {
	ID         string    `json:"id"`
	FamilyID   string    `json:"familyId"`
	Name       string    `json:"name"`
	DeviceID   string    `json:"deviceId"`
	DeviceName *string   `json:"deviceName,omitempty"`
	CreatedAt  time.Time `json:"createdAt"`
}

type DiaperActivity struct {
	ID            string         `json:"id"`
	ActivityType  ActivityType   `json:"activityType"`
	CreatedAt     time.Time      `json:"createdAt"`
	DiaperDetails *DiaperDetails `json:"diaperDetails,omitempty"`
}

func (DiaperActivity) IsActivity() {}

type DiaperDetails struct {
	ChangedAt time.Time `json:"changedAt"`
	HadPoop   bool      `json:"hadPoop"`
	HadPee    bool      `json:"hadPee"`
}

type DiaperDetailsInput struct {
	ChangedAt time.Time `json:"changedAt"`
	HadPoop   bool      `json:"hadPoop"`
	HadPee    *bool     `json:"hadPee,omitempty"`
}

type Family struct {
	ID         string       `json:"id"`
	Name       string       `json:"name"`
	BabyName   string       `json:"babyName"`
	Password   string       `json:"password"`
	Caregivers []*Caregiver `json:"caregivers"`
	CreatedAt  time.Time    `json:"createdAt"`
}

type FeedActivity struct {
	ID           string       `json:"id"`
	ActivityType ActivityType `json:"activityType"`
	CreatedAt    time.Time    `json:"createdAt"`
	FeedDetails  *FeedDetails `json:"feedDetails,omitempty"`
}

func (FeedActivity) IsActivity() {}

type FeedDetails struct {
	StartTime       time.Time   `json:"startTime"`
	EndTime         *time.Time  `json:"endTime,omitempty"`
	AmountMl        *int32      `json:"amountMl,omitempty"`
	FeedType        *FeedType   `json:"feedType,omitempty"`
	DurationMinutes *int32      `json:"durationMinutes,omitempty"`
	FoodName        *string     `json:"foodName,omitempty"`
	Quantity        *float64    `json:"quantity,omitempty"`
	QuantityUnit    *SolidsUnit `json:"quantityUnit,omitempty"`
}

type FeedDetailsInput struct {
	StartTime    time.Time   `json:"startTime"`
	EndTime      *time.Time  `json:"endTime,omitempty"`
	AmountMl     *int32      `json:"amountMl,omitempty"`
	FeedType     *FeedType   `json:"feedType,omitempty"`
	FoodName     *string     `json:"foodName,omitempty"`
	Quantity     *float64    `json:"quantity,omitempty"`
	QuantityUnit *SolidsUnit `json:"quantityUnit,omitempty"`
}

type Mutation struct {
}

type ParsedActivity struct {
	ActivityType  ActivityType   `json:"activityType"`
	FeedDetails   *FeedDetails   `json:"feedDetails,omitempty"`
	DiaperDetails *DiaperDetails `json:"diaperDetails,omitempty"`
	SleepDetails  *SleepDetails  `json:"sleepDetails,omitempty"`
}

type ParsedVoiceResult struct {
	Success          bool              `json:"success"`
	ParsedActivities []*ParsedActivity `json:"parsedActivities"`
	Errors           []string          `json:"errors,omitempty"`
	RawText          string            `json:"rawText"`
}

type Prediction struct {
	ID                       string                `json:"id"`
	ActivityType             ActivityType          `json:"activityType"`
	PredictionType           PredictionType        `json:"predictionType"`
	PredictedTime            time.Time             `json:"predictedTime"`
	Status                   PredictionStatus      `json:"status"`
	Confidence               *PredictionConfidence `json:"confidence,omitempty"`
	Reasoning                *string               `json:"reasoning,omitempty"`
	PredictedAmountMl        *int32                `json:"predictedAmountMl,omitempty"`
	PredictedDurationMinutes *int32                `json:"predictedDurationMinutes,omitempty"`
	CareSessionID            *string               `json:"careSessionId,omitempty"`
}

type Query struct {
}

type ScheduleGoals struct {
	TargetWakeWindowMinutes   *int32  `json:"targetWakeWindowMinutes,omitempty"`
	TargetFeedIntervalMinutes *int32  `json:"targetFeedIntervalMinutes,omitempty"`
	TargetNapCount            *int32  `json:"targetNapCount,omitempty"`
	MaxDaytimeNapMinutes      *int32  `json:"maxDaytimeNapMinutes,omitempty"`
	TargetBedtime             *string `json:"targetBedtime,omitempty"`
	TargetWakeTime            *string `json:"targetWakeTime,omitempty"`
}

type ScheduleGoalsInput struct {
	TargetWakeWindowMinutes   *int32  `json:"targetWakeWindowMinutes,omitempty"`
	TargetFeedIntervalMinutes *int32  `json:"targetFeedIntervalMinutes,omitempty"`
	TargetNapCount            *int32  `json:"targetNapCount,omitempty"`
	MaxDaytimeNapMinutes      *int32  `json:"maxDaytimeNapMinutes,omitempty"`
	TargetBedtime             *string `json:"targetBedtime,omitempty"`
	TargetWakeTime            *string `json:"targetWakeTime,omitempty"`
}

type SleepActivity struct {
	ID           string        `json:"id"`
	ActivityType ActivityType  `json:"activityType"`
	CreatedAt    time.Time     `json:"createdAt"`
	SleepDetails *SleepDetails `json:"sleepDetails,omitempty"`
}

func (SleepActivity) IsActivity() {}

type SleepDetails struct {
	StartTime       time.Time  `json:"startTime"`
	EndTime         *time.Time `json:"endTime,omitempty"`
	DurationMinutes *int32     `json:"durationMinutes,omitempty"`
	IsActive        *bool      `json:"isActive,omitempty"`
}

type SleepDetailsInput struct {
	StartTime time.Time  `json:"startTime"`
	EndTime   *time.Time `json:"endTime,omitempty"`
}

type ActivityType string

const (
	ActivityTypeFeed   ActivityType = "FEED"
	ActivityTypeDiaper ActivityType = "DIAPER"
	ActivityTypeSleep  ActivityType = "SLEEP"
)

var AllActivityType = []ActivityType{
	ActivityTypeFeed,
	ActivityTypeDiaper,
	ActivityTypeSleep,
}

func (e ActivityType) IsValid() bool {
	switch e {
	case ActivityTypeFeed, ActivityTypeDiaper, ActivityTypeSleep:
		return true
	}
	return false
}

func (e ActivityType) String() string {
	return string(e)
}

func (e *ActivityType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ActivityType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ActivityType", str)
	}
	return nil
}

func (e ActivityType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ActivityType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ActivityType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CareSessionStatus string

const (
	CareSessionStatusInProgress CareSessionStatus = "IN_PROGRESS"
	CareSessionStatusCompleted  CareSessionStatus = "COMPLETED"
)

var AllCareSessionStatus = []CareSessionStatus{
	CareSessionStatusInProgress,
	CareSessionStatusCompleted,
}

func (e CareSessionStatus) IsValid() bool {
	switch e {
	case CareSessionStatusInProgress, CareSessionStatusCompleted:
		return true
	}
	return false
}

func (e CareSessionStatus) String() string {
	return string(e)
}

func (e *CareSessionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CareSessionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CareSessionStatus", str)
	}
	return nil
}

func (e CareSessionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CareSessionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CareSessionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PredictionConfidence string

const (
	PredictionConfidenceHigh   PredictionConfidence = "HIGH"
	PredictionConfidenceMedium PredictionConfidence = "MEDIUM"
	PredictionConfidenceLow    PredictionConfidence = "LOW"
)

var AllPredictionConfidence = []PredictionConfidence{
	PredictionConfidenceHigh,
	PredictionConfidenceMedium,
	PredictionConfidenceLow,
}

func (e PredictionConfidence) IsValid() bool {
	switch e {
	case PredictionConfidenceHigh, PredictionConfidenceMedium, PredictionConfidenceLow:
		return true
	}
	return false
}

func (e PredictionConfidence) String() string {
	return string(e)
}

func (e *PredictionConfidence) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PredictionConfidence(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PredictionConfidence", str)
	}
	return nil
}

func (e PredictionConfidence) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PredictionConfidence) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PredictionConfidence) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PredictionStatus string

const (
	PredictionStatusOverdue  PredictionStatus = "OVERDUE"
	PredictionStatusUpcoming PredictionStatus = "UPCOMING"
	PredictionStatusPlanned  PredictionStatus = "PLANNED"
)

var AllPredictionStatus = []PredictionStatus{
	PredictionStatusOverdue,
	PredictionStatusUpcoming,
	PredictionStatusPlanned,
}

func (e PredictionStatus) IsValid() bool {
	switch e {
	case PredictionStatusOverdue, PredictionStatusUpcoming, PredictionStatusPlanned:
		return true
	}
	return false
}

func (e PredictionStatus) String() string {
	return string(e)
}

func (e *PredictionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PredictionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PredictionStatus", str)
	}
	return nil
}

func (e PredictionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PredictionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PredictionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PredictionType string

const (
	PredictionTypeNextFeed PredictionType = "NEXT_FEED"
	PredictionTypeNextNap  PredictionType = "NEXT_NAP"
	PredictionTypeNextWake PredictionType = "NEXT_WAKE"
	PredictionTypeBedtime  PredictionType = "BEDTIME"
)

var AllPredictionType = []PredictionType{
	PredictionTypeNextFeed,
	PredictionTypeNextNap,
	PredictionTypeNextWake,
	PredictionTypeBedtime,
}

func (e PredictionType) IsValid() bool {
	switch e {
	case PredictionTypeNextFeed, PredictionTypeNextNap, PredictionTypeNextWake, PredictionTypeBedtime:
		return true
	}
	return false
}

func (e PredictionType) String() string {
	return string(e)
}

func (e *PredictionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PredictionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PredictionType", str)
	}
	return nil
}

func (e PredictionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PredictionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PredictionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
