package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/swatkatz/babybaton/backend/graph/model"
)

// PredictNextFeed is the resolver for the predictNextFeed field.
func (r *queryResolver) PredictNextFeed(ctx context.Context) (*model.NextFeedPrediction, error) {
	return GetMockPrediction(), nil
}

// GetCurrentSession is the resolver for the getCurrentSession field.
func (r *queryResolver) GetCurrentSession(ctx context.Context) (*model.CareSession, error) {
	return GetMockCurrentSession(), nil
}

// GetRecentCareSessions is the resolver for the getRecentCareSessions field.
func (r *queryResolver) GetRecentCareSessions(ctx context.Context, limit *int32) ([]*model.CareSession, error) {
	return GetMockRecentSessions(), nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
